# Generated by Django 5.2.5 on 2025-08-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('table_name', models.CharField(blank=True, max_length=50, null=True)),
                ('record_id', models.IntegerField(blank=True, null=True)),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CleaningRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleaning_date', models.DateField()),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('washing_start_time', models.DateTimeField(blank=True, null=True)),
                ('washing_end_time', models.DateTimeField(blank=True, null=True)),
                ('water_pressure', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('air_pressure', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('drying_start_time', models.DateTimeField(blank=True, null=True)),
                ('drying_end_time', models.DateTimeField(blank=True, null=True)),
                ('drying_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_drying_time', models.IntegerField(blank=True, null=True)),
                ('cleaning_status', models.CharField(choices=[('satisfactory', 'Satisfactory'), ('rework', 'Rework'), ('rejected', 'Rejected')], default='satisfactory', max_length=20)),
                ('operator_signature', models.TextField(blank=True, null=True)),
                ('supervisor_signature', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
