# Generated by Django 5.2.5 on 2025-08-28 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cleaning', '0001_initial'),
        ('filters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cleaningrecord',
            name='filter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filters.filter'),
        ),
        migrations.AddField(
            model_name='cleaningrecord',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_operator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cleaningrecord',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_supervisor', to=settings.AUTH_USER_MODEL),
        ),
    ]
