# Generated by Django 5.2.5 on 2025-08-28 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AHU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ahu_number', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('booth_number', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FilterType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('default_cleaning_interval_days', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_id', models.CharField(max_length=50, unique=True)),
                ('cleaning_interval_days', models.IntegerField()),
                ('last_cleaned_date', models.DateField(blank=True, null=True)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('due', 'Due'), ('cleaning', 'Cleaning'), ('drying', 'Drying'), ('cleaned', 'Cleaned'), ('rejected', 'Rejected')], default='active', max_length=20)),
                ('qr_code_data', models.TextField(blank=True, null=True)),
                ('ahu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filters.ahu')),
                ('filter_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filters.filtertype')),
            ],
        ),
        migrations.AddField(
            model_name='ahu',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filters.plant'),
        ),
    ]
